export {default as Main} from './Main'
export {default as Navbar} from './Navbar'
export {default as Posts} from './Posts'
export {default as Register} from './Register'
export {default as Login} from './Login'
export {default as CreatePosts} from './CreatePosts'
export {default as PostDetails} from './PostDetails'
export {default as MyMessages} from './MyMessages'
export {default as MessageForm} from './MessageForm'
export {default as PostSearch} from './PostSearch'
export {default as Profile} from './Profile'
// export {default as SinglePost} from './SinglePost'

